name: daily-cron
on:
  schedule:
    - cron: "0 11 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: |
          curl --request POST \
          --url 'https://real-me.vercel.app/api/reals/send'
